"use client";

import { Download } from "lucide-react";
import { useState } from "react";
import type { MeetingAnalysis } from "@/types/meeting";

export function ExportPDF({ analysis }: { analysis: MeetingAnalysis }) {
  const [exporting, setExporting] = useState(false);

  function exportPDF() {
    setExporting(true);

    const items = analysis.actionItems.map(i =>
      `  [${i.id}] ${i.task}\n  Owner: ${i.owner} | Due: ${i.dueDate} | Risk: ${i.risk.toUpperCase()} (${i.riskScore}/100)${i.blockers.length ? `\n  Blockers: ${i.blockers.join(", ")}` : ""}`
    ).join("\n\n");

    const decisions = analysis.decisions.map(d => `  • ${d.decision}`).join("\n");
    const questions = analysis.openQuestions.map(q => `  • ${q.question} (Owner: ${q.suggestedOwner})`).join("\n");

    const content = `
ACCOUNTABILITY AGENT REPORT
════════════════════════════════════════════════════════════════

Meeting: ${analysis.title}
Date: ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
Accountability Score: ${analysis.accountabilityScore}/100

────────────────────────────────────────────────────────────────
EXECUTIVE SUMMARY
────────────────────────────────────────────────────────────────
${analysis.executiveSummary}

────────────────────────────────────────────────────────────────
ACTION ITEMS (${analysis.actionItems.length} total)
────────────────────────────────────────────────────────────────
${items}

────────────────────────────────────────────────────────────────
DECISIONS MADE (${analysis.decisions.length})
────────────────────────────────────────────────────────────────
${decisions || "  None recorded."}

────────────────────────────────────────────────────────────────
OPEN QUESTIONS (${analysis.openQuestions.length})
────────────────────────────────────────────────────────────────
${questions || "  None recorded."}

────────────────────────────────────────────────────────────────
FOLLOW-UP EMAIL DRAFT
────────────────────────────────────────────────────────────────
${analysis.followUpEmail}

────────────────────────────────────────────────────────────────
Generated by Teams Accountability Agent · Work IQ powered
${new Date().toISOString()}
════════════════════════════════════════════════════════════════
`.trim();

    // Create blob and download
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${analysis.title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}_report.txt`;
    a.click();
    URL.revokeObjectURL(url);

    setTimeout(() => setExporting(false), 1000);
  }

  return (
    <button
      type="button"
      onClick={exportPDF}
      disabled={exporting}
      style={{
        display: "flex", alignItems: "center", gap: "8px",
        padding: "10px 18px", borderRadius: "8px", cursor: "pointer",
        background: "rgba(201,168,76,0.08)", border: "1px solid #8a6d2e",
        color: "#c9a84c", fontSize: "13px", fontWeight: 600,
        transition: "all 0.15s"
      }}
      onMouseEnter={e => { e.currentTarget.style.background = "rgba(201,168,76,0.15)"; }}
      onMouseLeave={e => { e.currentTarget.style.background = "rgba(201,168,76,0.08)"; }}
    >
      <Download size={15} />
      {exporting ? "Exporting…" : "Export report"}
    </button>
  );
}
